dental_clinic_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('patient/', include('patient.urls', namespace='patient')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

patient/urls.py
from django.urls import path
from .views import *

app_name = 'patient'

urlpatterns = [
    # Page urls
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('price/', price, name='price'),
    path('team/', team, name='team'),
    path('testimonial/', testimonial, name='testimonial'),
    path('appointment/', appointment, name='appointment'),
    path('contact/', contact, name='contact'),

    # Authentication urls
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('register/', register, name='register'),
    path('profile/', ProfileUserView.as_view(), name='profile'),

    # Main url(Make Appointment)
    path('make_appointment/', make_appointment, name='make_appointment'),
    path('appointment_history/', appointment_history, name='appointment_history'),
]

patient/models.py
from django.db import models
from django.contrib.auth.models import User

class Service(models.Model):
    name = models.CharField(max_length=255, db_index=True, unique=True)
    image = models.ImageField(max_length=255, upload_to='service', null=True)
    class_name = models.CharField(max_length=255, null=True)
    
    def __str__(self):
        return self.name
    

class Doctor(models.Model):
    name = models.CharField(max_length=255, db_index=True, unique=True)
    image = models.ImageField(max_length=255, upload_to='doctor')
    special_name = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="doctor_speciality")
    class_name = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name

class Date(models.Model):
    day = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.day

class Time(models.Model):
    time = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.time

class Appointment(models.Model):
    user_name = models.ForeignKey(User, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="service")
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name="doctor")
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=255, null=True, blank=True)
    app_date = models.ForeignKey(Date, on_delete=models.CASCADE, related_name="app_date", max_length=255)
    app_time = models.ForeignKey(Time, on_delete=models.CASCADE, related_name="app_time", max_length=255)

    def __str__(self):
        return f"{self.user_name}-{self.name}"
    

patient/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model

class LoginForm(forms.Form):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)


class RegisterForm(forms.ModelForm):
    username = forms.CharField(label="Username")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput)

    class Meta:
        model = get_user_model()
        fields = ('username','email','password','password2', 'first_name', 'last_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Kiritilgan passwordlar bir-biriga mos kelmadi!")
        return cd['password']

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("Oldin bunday email bilan ro'yhatdan o'tilgan!")
        return email


class ProfileForm(forms.ModelForm):
    username = forms.CharField(label="Username", disabled=True)
    email = forms.EmailField(label="Email", disabled=True)

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'email')

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['service', 'doctor', 'name', 'email', 'app_date', 'app_time']

patient/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .models import *
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import UpdateView
from .forms import *
from django.views.decorators.csrf import requires_csrf_token

data = {
    "services": Service.objects.all(),
    "doctors": Doctor.objects.all(),
    "days": Date.objects.all(),
    "times": Time.objects.all(),
    "appointments": Appointment.objects.all(),
}


def index(request):
    return render(request, 'patient/index.html', context=data)

def about(request):
    return render(request, 'patient/about.html', context=data)

def service(request):
    return render(request, 'patient/service.html', context=data)

def price(request):
    return render(request, 'patient/price.html', context=data)

def team(request):
    return render(request, 'patient/team.html', context=data)

def testimonial(request):
    return render(request, 'patient/testimonial.html', context=data)

def appointment(request):
    return render(request, 'patient/appointment.html', context=data)

def login(request):
    return render(request, 'patient/login.html', context=data)

def contact(request):
    return render(request, 'patient/contact.html', context=data)

def user_login(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = authenticate(username=cleaned_data['username'], password=cleaned_data['password'])
            if user is not None and user.is_active:
                auth_login(request,user)
                messages.success(request, ("You are now logged in successfully!"))
                return HttpResponseRedirect(reverse('patient:index'))
    data['form'] = form
    return render(request, 'patient/login.html', context=data)

def user_logout(request):
    logout(request)
    messages.success(request, ("You are now logged out successfully!"))
    return HttpResponseRedirect(reverse('patient:login'))

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return HttpResponseRedirect(reverse('patient:login'))
    data['form'] = form
    return render(request, 'patient/register.html', context=data)

class ProfileUserView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileForm
    template_name = 'patient/profile.html'

    def get_success_url(self):
        return reverse_lazy('patient:index')

    def get_object(self):
        return self.request.user


@login_required(login_url="patient:login")
def make_appointment(request):
    try:
        if request.method == 'POST':
            print(request.POST)
            exist_app = Appointment.objects.filter(
                doctor = get_object_or_404(Doctor, pk=request.POST.get('doctor')),
                app_date = get_object_or_404(Date, pk=request.POST.get('weekday')),
                app_time = get_object_or_404(Time, pk=request.POST.get('time'))
            )
            if exist_app.exists():
                messages.success(request, ("Bu vaqtda belgilagan doktor uchun joy oldin band qilingan. Boshqa vaqtda yoki boshqa doktorimiz tomonidan sizga xizmat ko'rsatsak mamnun bo'lamiz!"))
                return HttpResponseRedirect(reverse('patient:index'))
                
            Appointment.objects.create(
                user_name = get_object_or_404(User, pk=request.user.id),
                service = get_object_or_404(Service, pk=request.POST.get('service')),
                doctor = get_object_or_404(Doctor, pk=request.POST.get('doctor')),
                name = request.POST.get('name'),      
                email = request.POST.get('email'),
                app_date = get_object_or_404(Date, pk=request.POST.get('weekday')),
                app_time = get_object_or_404(Time, pk=request.POST.get('time'))
            )
            messages.success(request, ("Berilgan vaqtda joy band qildingiz. Sizga xizmat ko'rsatishdan xursandmiz!"))
            return HttpResponseRedirect(reverse('patient:index'))
        return render(request, 'patient/index.html', context=data)
    
    except Exception as e:
        messages.success(request, (f"Occured error: {e}!"))
            

def appointment_history(request):
    data['appointments'] = Appointment.objects.filter(user_name=request.user)
    return render(request, 'patient/history.html', context=data)

patient/templates/patient/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">About Us</h1>
                <a href="{% url 'patient:index' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'patient:about' %}" class="h4 text-white">About</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- About Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title mb-4">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">About Us</h5>
                        <h1 class="display-5 mb-0">The World's Best Dental Clinic That You Can Trust</h1>
                    </div>
                    <h4 class="text-body fst-italic mb-4">Diam dolor diam ipsum sit. Clita erat ipsum et lorem stet no lorem sit clita duo justo magna dolore</h4>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                    <div class="row g-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.3s">
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Award Winning</h5>
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Professional Staff</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.6s">
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>24/7 Opened</h5>
                            <h5 class="mb-3"><i class="fa fa-check-circle text-primary me-3"></i>Fair Prices</h5>
                        </div>
                    </div>
                    <a href="{% url 'patient:appointment' %}" class="btn btn-primary py-3 px-5 mt-4 wow zoomIn" data-wow-delay="0.6s">Make Appointment</a>
                </div>
                <div class="col-lg-5" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100 rounded wow zoomIn" data-wow-delay="0.9s" src="{% static 'img/about.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
    

{% endblock content %}

patient/templates/patient/appointment.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Appointment</h1>
                <a href="{% url 'patient:index' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'patient:appointment' %}" class="h4 text-white">Appointment</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Appointment Start -->
    <div class="container-fluid bg-primary bg-appointment mb-5 wow fadeInUp" data-wow-delay="0.1s" style="margin-top: 90px;">
        <div class="container">
            <div class="row gx-5">
                <div class="col-lg-6 py-5">
                    <div class="py-5">
                        <h1 class="display-5 text-white mb-4">We Are A Certified and Award Winning Dental Clinic You Can Trust</h1>
                        <p class="text-white mb-0">Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo rebum sea invidunt voluptua. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo invidunt lorem. Elitr ut dolores magna sit. Sea dolore sanctus sed et. Takimata takimata sanctus sed.</p>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="appointment-form h-100 d-flex flex-column justify-content-center text-center p-5 wow zoomIn" data-wow-delay="0.6s">
                        <h1 class="text-white mb-4">Make Appointment</h1>
                        <form action="{% url 'patient:make_appointment' %}" method="post">
                            {% csrf_token %}
                            <div class="row g-3">
                                <div class="col-12 col-sm-6">
                                    <select name="service" class="form-select bg-light border-0" style="height: 55px;">
                                        <option selected>Select A Service</option>
                                        {% for service in services %}
                                            <option value={{service.id}}>{{service.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select name="doctor" class="form-select bg-light border-0" style="height: 55px;">
                                        <option selected>Select Doctor</option>
                                        {% for doctor in doctors %}
                                            <option value={{doctor.id}}>{{doctor.name}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input name="name" type="text" class="form-control bg-light border-0" placeholder="Your Name" style="height: 55px;">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <input name="email" type="text" class="form-control bg-light border-0" placeholder="Your Email" style="height: 55px;", value="">
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select name="weekday" class="form-select bg-light border-0" style="height: 55px;">
                                        <option selected>Select Weekday</option>
                                        {% for day in days %}
                                            <option value={{day.id}}>{{day.day}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12 col-sm-6">
                                    <select name="time" class="form-select bg-light border-0" style="height: 55px;">
                                        <option selected>Select Time</option>
                                        {% for time in times %}
                                            <option value={{time.id}}>{{time.time}}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="col-12">
                                    <button class="btn btn-dark w-100 py-3" type="submit"  id="btn-appointment">Make Appointment</button>
                                </div>
                            </div>  
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Appointment End -->
    

{% endblock content %}

patient/templates/patient/contact.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Contact Us</h1>
                <a href="{% url 'patient:index' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'patient:contact' %}" class="h4 text-white">Contact</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-xl-4 col-lg-6 wow slideInUp" data-wow-delay="0.1s">
                    <div class="bg-light rounded h-100 p-5">
                        <div class="section-title">
                            <h5 class="position-relative d-inline-block text-primary text-uppercase">Contact Us</h5>
                            <h1 class="display-6 mb-4">Feel Free To Contact Us</h1>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <i class="bi bi-geo-alt fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Our Office</h5>
                                <span>123 Street, New York, USA</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center mb-2">
                            <i class="bi bi-envelope-open fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Email Us</h5>
                                <span>info@example.com</span>
                            </div>
                        </div>
                        <div class="d-flex align-items-center">
                            <i class="bi bi-phone-vibrate fs-1 text-primary me-3"></i>
                            <div class="text-start">
                                <h5 class="mb-0">Call Us</h5>
                                <span>+012 345 6789</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-4 col-lg-6 wow slideInUp" data-wow-delay="0.3s">
                    <form>
                        <div class="row g-3">
                            <div class="col-12">
                                <input type="text" class="form-control border-0 bg-light px-4" placeholder="Your Name" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <input type="email" class="form-control border-0 bg-light px-4" placeholder="Your Email" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <input type="text" class="form-control border-0 bg-light px-4" placeholder="Subject" style="height: 55px;">
                            </div>
                            <div class="col-12">
                                <textarea class="form-control border-0 bg-light px-4 py-3" rows="5" placeholder="Message"></textarea>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-xl-4 col-lg-12 wow slideInUp" data-wow-delay="0.6s">
                    <iframe class="position-relative rounded w-100 h-100"
                        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                        frameborder="0" style="min-height: 400px; border:0;" allowfullscreen="" aria-hidden="false"
                        tabindex="0"></iframe>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


{% endblock content %}

patient/templates/patient/price.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Pricing</h1>
                <a href="{% url 'patient:index' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'patient:price' %}" class="h4 text-white">Pricing</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Pricing Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-5">
                    <div class="section-title mb-4">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Pricing Plan</h5>
                        <h1 class="display-5 mb-0">We Offer Fair Prices for Dental Treatment</h1>
                    </div>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo eirmod magna dolore erat amet</p>
                    <h5 class="text-uppercase text-primary wow fadeInUp" data-wow-delay="0.3s">Call for Appointment</h5>
                    <h1 class="wow fadeInUp" data-wow-delay="0.6s">+012 345 6789</h1>
                </div>
                <div class="col-lg-7">
                    <div class="owl-carousel price-carousel wow zoomIn" data-wow-delay="0.9s">
                        <div class="price-item pb-4">
                            <div class="position-relative">
                                <img class="img-fluid rounded-top" src="{% static 'img/price-1.jpg' %}" alt="">
                                <div class="d-flex align-items-center justify-content-center bg-light rounded pt-2 px-3 position-absolute top-100 start-50 translate-middle" style="z-index: 2;">
                                    <h2 class="text-primary m-0">$35</h2>
                                </div>
                            </div>
                            <div class="position-relative text-center bg-light border-bottom border-primary py-5 p-4">
                                <h4>Teeth Whitening</h4>
                                <hr class="text-primary w-50 mx-auto mt-0">
                                <div class="d-flex justify-content-between mb-3"><span>Modern Equipment</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-3"><span>Professional Dentist</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-2"><span>24/7 Call Support</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <a href="{% url 'patient:appointment' %}" class="btn btn-primary py-2 px-4 position-absolute top-100 start-50 translate-middle">Appointment</a>
                            </div>
                        </div>
                        <div class="price-item pb-4">
                            <div class="position-relative">
                                <img class="img-fluid rounded-top" src="{% static 'img/price-2.jpg' %}" alt="">
                                <div class="d-flex align-items-center justify-content-center bg-light rounded pt-2 px-3 position-absolute top-100 start-50 translate-middle" style="z-index: 2;">
                                    <h2 class="text-primary m-0">$49</h2>
                                </div>
                            </div>
                            <div class="position-relative text-center bg-light border-bottom border-primary py-5 p-4">
                                <h4>Dental Implant</h4>
                                <hr class="text-primary w-50 mx-auto mt-0">
                                <div class="d-flex justify-content-between mb-3"><span>Modern Equipment</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-3"><span>Professional Dentist</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-2"><span>24/7 Call Support</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <a href="{% url 'patient:appointment' %}" class="btn btn-primary py-2 px-4 position-absolute top-100 start-50 translate-middle">Appointment</a>
                            </div>
                        </div>
                        <div class="price-item pb-4">
                            <div class="position-relative">
                                <img class="img-fluid rounded-top" src="{% static 'img/price-3.jpg' %}" alt="">
                                <div class="d-flex align-items-center justify-content-center bg-light rounded pt-2 px-3 position-absolute top-100 start-50 translate-middle" style="z-index: 2;">
                                    <h2 class="text-primary m-0">$99</h2>
                                </div>
                            </div>
                            <div class="position-relative text-center bg-light border-bottom border-primary py-5 p-4">
                                <h4>Root Canal</h4>
                                <hr class="text-primary w-50 mx-auto mt-0">
                                <div class="d-flex justify-content-between mb-3"><span>Modern Equipment</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-3"><span>Professional Dentist</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <div class="d-flex justify-content-between mb-2"><span>24/7 Call Support</span><i class="fa fa-check text-primary pt-1"></i></div>
                                <a href="{% url 'patient:appointment' %}" class="btn btn-primary py-2 px-4 position-absolute top-100 start-50 translate-middle">Appointment</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Pricing End -->
    

{% endblock content %}

patient/templates/patient/team.html
{% extends "base.html" %}
{% load static %}

{% block content %}


    <!-- Hero Start -->
    <div class="container-fluid bg-primary py-5 hero-header mb-5">
        <div class="row py-3">
            <div class="col-12 text-center">
                <h1 class="display-3 text-white animated zoomIn">Dentist</h1>
                <a href="{% url 'patient:index' %}" class="h4 text-white">Home</a>
                <i class="far fa-circle text-white px-2"></i>
                <a href="{% url 'patient:team' %}" class="h4 text-white">Dentist</a>
            </div>
        </div>
    </div>
    <!-- Hero End -->


    <!-- Team Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="row g-5">
                <div class="col-lg-4 wow slideInUp" data-wow-delay="0.1s">
                    <div class="section-title bg-light rounded h-100 p-5">
                        <h5 class="position-relative d-inline-block text-primary text-uppercase">Our Dentist</h5>
                        <h1 class="display-6 mb-4">Meet Our Certified & Experienced Dentist</h1>
                        <a href="{% url 'patient:appointment' %}" class="btn btn-primary py-3 px-5">Appointment</a>
                    </div>
                </div>
                {% for doctor in doctors %}
                    <div class="col-lg-4 wow slideInUp" data-wow-delay={{doctor.class_name}}>
                        <div class="team-item">
                            <div class="position-relative rounded-top" style="z-index: 1;">
                                <img class="img-fluid rounded-top w-100" src="{{doctor.image.url}}" alt="">
                                <div class="position-absolute top-100 start-50 translate-middle bg-light rounded p-2 d-flex">
                                    <a class="btn btn-primary btn-square m-1" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                                    <a class="btn btn-primary btn-square m-1" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                                    <a class="btn btn-primary btn-square m-1" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                                    <a class="btn btn-primary btn-square m-1" href="#"><i class="fab fa-instagram fw-normal"></i></a>
                                </div>
                            </div>
                            <div class="team-text position-relative bg-light text-center rounded-bottom p-4 pt-5">
                                <h4 class="mb-2">Dr. {{doctor.name}}</h4>
                                <p class="text-primary mb-0">{{doctor.speciality}}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Team End -->
    
    

{% endblock content %}